server:
  port: 8080

spring:
  application:
    name: GiftLedger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giftledger
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update

jwt:
  secret: ThisIsAVeryLongAndSecureSecretKeyForJWTTokenGenerationThatMeetsTheMinimumRequirementOf256BitsOrMoreForHS256AlgorithmToWorkProperlyWithoutAnyIssues
  expiration: 86400000

logging:
  level:
    root: info
    springboot:
      giftledger: debug
    org:
      springframework:
        security: debug
