spring:
  application:
    name: GiftLedger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giftledger
    username: root
    password: 1234

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        ddl-auto: update
        show-sql: true

jwt:
  secret: "1a2b3c4d5e6f7g8h9i0j"

